apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image:  "suraj2143/sample-profile:1"
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3002
              protocol: TCP
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URL
              value: "mongodb+srv://travelMemory:cKzcCPpLsRn79eOE@surajcluster.pc4bi2z.mongodb.net/?retryWrites=true&w=majority"